services:
  ubuntu:
    container_name: openu
    build:
      context: .
      args:
        - USERNAME=${USERNAME}
        - PASSWORD=${PASSWORD}
    environment:
      - USERNAME=${USERNAME}
    volumes:
      - ./internal:/home/${USERNAME}
    restart: on-failure
    command: ["sleep","infinity"]

